apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: test
spec:
  selector:
    app: app
  ports:
    - name: web
      port: 30
      targetPort: 30
    - name: admin
      port: 31
      targetPort: 31
